# Generated by Django 4.0 on 2024-05-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
